CHANGELOG.md, README.md, data/common.yaml, manifests/init.pp, manifests/linux/patchday.pp, manifests/windows/patchday.pp, metadata.json
- Ensures pending reboots are handled correctly, skipping patch installs completely
- Allows defining `Exec` resources dynamically for pre/post-patching & pre-reboot commands
- Refactors reboot logic into main manifest
=> Pre post reboot control

CHANGELOG.md, REFERENCE.md, lib/facter/metered_link.rb, lib/patching_as_code/metered_link.ps1, manifests/init.pp, metadata.json
This PR adds control for patching over metered links. By default, when a metered link is detected (Windows only), this module will skip patching. You can control this behavior through the `patch_on_metered_links` parameter.
=> Add control for metered links

CHANGELOG.md, lib/facter/metered_link.rb, lib/patching_as_code/metered_link.ps1, manifests/init.pp, metadata.json
This PR fixes the metered_link fact to be reported as a Boolean. It was accidentally interpreted as a String, which broke the logic in the Puppet code.
=> Version 0.2.4: fix datatype of metered_link fact

CHANGELOG.md, README.md, REFERENCE.md, data/common.yaml, lib/facter/patch_unsafe_process_active.rb, manifests/init.pp, metadata.json
- Added a `patch_unsafe_process_active` custom fact that reflects if any process from the `unsafe_process_list` parameter was found active on the system.
- Added a `unsafe_process_list` parameter to the `patching_as_code` class, which defines processes for the system that must cause patching to be skipped if any of those processes are active. Defaults to an empty array.
=> v0.2.6 - skip patching if an unsafe process is active

CHANGELOG.md, manifests/linux/patchday.pp, manifests/windows/patchday.pp, metadata.json
This PR changes the Linux patchday code to use a resource collector and the `ensure_packages()` function to define the patch package in a way that prevents possible duplicate resource declarations.
Fixes Issue #10
=> Fix risk of duplicate declarations

CHANGELOG.md, manifests/init.pp, manifests/linux/patchday.pp, metadata.json
This PR helps further protect against duplicate package declarations when `ensure` is set to a version. This isn't 100% bulletproof as the check is parse-order-dependent, but will work in most cases.
=> Support existing package declarations that specify a version

CHANGELOG.md, README.md, REFERENCE.md, data/common.yaml, functions/is_patchday.pp, manifests/init.pp, metadata.json
- Adds support for providing an array of values to the `patch_group` attribute of the `patching_as_code` class
- Adds support for providing an array of values to the `count_of_week` parameter in a patch schedule
=> v0.6.0 - patch_group and scheduling improvements

CHANGELOG.md, manifests/init.pp, metadata.json
Removed the `weekday` attribute of the `schedule` resource that this module uses internally to restrict when patches can be applied. In certain edge cases where the Puppet server is in a very different timezone from a managed node, there can be a 1 day date difference between the two systems. This creates a scenario where the node never receives a valid patch schedule. By removing the `weekday` parameter from the `schedule` resource, this can no longer occur. Other logic still protects the actual day on which the patching is allowed so this parameter wasn't necessary.
=> v0.6.1 - Fix wide timezone difference case

metadata.json
Updated puppetlabs/powershell boundary. The new version of the PowerShell module only drops Puppet 5 support, which this module doesn't have anyway.
=> Update boundaries for powershell

CHANGELOG.md, manifests/init.pp, manifests/linux/patchday.pp, manifests/reboot.pp, manifests/windows/patchday.pp, metadata.json
- Moves the post-patch reboot logic to its own stage (`patch_reboot`), which runs after the `main` stage. This should ensure that reboots only happen at the end of the Puppet run.
- Removed the `notify` logic for triggering the reboots from installed patches, in favor of handling the reboot logic in the new `patch_reboot` stage.
- Deduplicated the calling of the Exec resource that refreshes the patch fact, ensuring this only happens once now.
=> Move post-patch reboot logic to its own stage that runs after [main]

CHANGELOG.md, lib/puppet/type/patch_package.rb, manifests/init.pp, manifests/linux/patchday.pp, manifests/windows/patchday.pp, metadata.json
**Improvements**
- Adopted the `eval_generate` function in the `patch_package` type to ensure that newly generated `package` resources become children of the `patching_as_code::linux::patchday` class. This provides better context for these package resources, which can be leveraged in external reporting tools (e.g. Splunk).
- Simplified the `patch_package` type, removed capabilities that are no longer needed
- Moved the logic to trigger the patch fact refresh to the main manifest
- Simplified the patchday classes
=> v0.7.1 - code improvements

CHANGELOG.md, manifests/init.pp, metadata.json
**Bugfixes**
- Fixes a missing `schedule` metaparameter for the `Notify[Patching as Code - Update Fact]`, which would cause the `pe_patch` fact to update at every Puppet run during the patch day, instead of only during the maintenance window.
=> v0.7.4: schedule fix in Notify resource

CHANGELOG.md, manifests/init.pp, metadata.json
This PR deduplicates the array of patches before passing it to the patchday manifest, preventing possible duplicate resource declaration errors. This fixes issue #39.
=> v0.7.11: Fix issues caused by duplicate items in list of patches

functions/is_patchday.pp
resolves: ```Warning: Calling function empty() with Numeric value is deprecated.
(file: /workspace/modules/patching_as_code/functions/is_patchday.pp, line: 7)```
=> work around deprecation message

README.md, manifests/init.pp
Ran into an issue where customer's use case failed sending facts, os_patching module's default. Added the optional boolean to accommodate, updated README usage section.
=> backward-compatible disabling of os_patching's fact_upload

CHANGELOG.md, lib/facter/patching_as_code_choco.rb, metadata.json
**Bugfixes**
- Improved processing of the `patching_as_config_choco` fact, to ensure backwards compatibility with Facter 3.
- The `patching_as_config_choco` fact now no longer errors on a system that does not have `patching_as_config` enabled.
=> v1.0.1: Improve handling of `patching_as_code_choco` fact

CHANGELOG.md, README.md, data/common.yaml, manifests/init.pp, metadata.json
**Improvements**
- Split the `allowlist` and `blacklist` to have dedicated lists for Chocolatey, with the new `allowlist_choco` and `blacklist_choco` parameters. These new parameters now must be used for Chocolatey packages, the regular `allowlist` and `blacklist` will not affect Chocolatey packages anymore.
- Pending OS reboots will now no longer occur if `enable_patching` has been changed to `false`. This is to enable the `enable_patching` parameter being used as a single switch to ensure that no disruptive action can happen at all.
=> v1.0.2: Unique allow/block lists for Chocolatey

CHANGELOG.md, lib/facter/patching_as_code.rb, manifests/init.pp, metadata.json
* Moves the location of the `patching_as_code` fact content to `/opt/puppetlabs/patching_as_code` (or `%ProgramData%\PuppetLabs\patching_as_code` on Windows), to remove a dependency on `pe_patch/os_patching` creating the directory where the last_run file content can be stored.
* Fixes an incompatibility with `os_patching` that was caused by the wrong directory being assumed for the `patching_as_code` fact content when using `os_patching`. Documented in #48
=> v1.0.5: Use own location for `patching_as_code` fact

CHANGELOG.md, README.md, REFERENCE.md, data/common.yaml, functions/process_patch_groups.pp, lib/facter/patching_as_code.rb, lib/puppet/functions/patching_as_code/high_prio_last_run.rb, manifests/high_prio_reboot.pp, manifests/init.pp, manifests/linux/patchday.pp, manifests/windows/patchday.pp, metadata.json
**Features**
- Adds support for high priority patches on an alternate patch schedule.
- Adds `high_priority_only` parameter to the `patching_as_code` class, for compatibility with the `puppetlabs/change_window` module.
**Improvements**
- Ensures the last_run fact data only gets written during the patch window.
=> v1.1.0: High priority patching support

CHANGELOG.md, manifests/init.pp, manifests/windows/patchday.pp, metadata.json
**Bugfixes**
- Fixes a bug that caused High Priority OS patches for Windows not to be installed, due to the wrong variable being used.
**Improvements**
- Deduplicates the list of installed patches on the last run, reported in the `patching_as_code` fact.
=> v1.1.2: Fix High Priority patches not getting installed on Windows

README.md
You can customize this slightly to say "Puppet Community and the Sales
Engineers team" or similar if you like, as long as you don't change the
gist of the supportability status.
=> Added the Trusted Contributor notice

lib/patching_as_code/pending_reboot.sh, metadata.json
This appears to be all that is required to get RHEL9 support enabled for this module.
It appears to be the root cause of my bug in #63
=> Add RHEL9 support to pending_reboot.sh

manifests/init.pp
**Bugfixes**
- Adjusted the `onlyif` logic in the resources created by `patching_as_code::pre_reboot_commands` to ensure that these commands only execute when there is either a pending OS reboot that needs to be honered, or if there are >0 patches to install and `reboot: always` is used.
=> v1.1.6: improved logic for pre_reboot_commands

lib/facter/patching_as_code.rb
Previously, the 'patching_as_code' fact was executing on all operating systems, including Darwin (macOS) systems. However, the fact is not applicable to Darwin systems, and executing it on those platforms can cause unnecessary overhead.
This commit modifies the fact code by adding the necessary conditions to exclude the 'patching_as_code' fact from running on Darwin systems. The fact will now only execute on Windows and Linux systems, improving efficiency and avoiding any potential issues on unsupported platforms.
By excluding the 'patching_as_code' fact from running on Darwin systems, we ensure that the fact execution is limited to the relevant operating systems, aligning with the intended behavior of the code.
=> Exclude 'patching_as_code' fact from running on Darwin systems

lib/facter/metered_link.rb, lib/puppet/type/reboot_if_pending.rb
Implemented fix suggested in #95
Tested on Windows server 2022
=>  Powershell scripts should be executed with the -NoProfile parameter
